#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; TMP_WORK_DIR="$2"; REV="$3"

[[ ! -f "$TMP_WORK_DIR/.dokku-monorepo" ]] && exit

dokku_log_info2 "Monorepo detected"

while IFS="=" read -u 10 -a line || [[ -n $line ]]; do
  [[ "${line[0]}" == "#"* || "${line[1]}" == "" ]] && continue
  [[ $APP != *"${line[0]}"* ]] && continue

  app_subdir="${line[1]}"
  dockerfile_path="${TMP_WORK_DIR}/${app_subdir}/Dockerfile"

  [[ ! -e $dockerfile_path ]] && \
    dokku_log_info2 "The application $APP is missing a Dockerfile at $app_subdir/Dockerfile" && \
    exit 1

  dokku_log_info2 "Building using Dockerfile from ./$app_subdir"
  cp $dockerfile_path Dockerfile

  exit
done 10<"$TMP_WORK_DIR/.dokku-monorepo"

dokku_log_info2 "The application $APP is not defined in .dokku-monorepo!"
exit 1
